public enum action {
    MAIN_MENU,
    ADD_STUDENT,
    REMOVE_STUDENT,
    SEARCH_STUDENT,
    ADD_GRADE,
    CALC_AVERAGE,
    AC_ZODIAC,
    AC_LEAPYEAR,
    COUNTALL,
    CALC_FAVERAGE,
    PRINTABC,
    TESTING,
    END
}
